export const Lottery = {
    LUCKY_WORD_ADDED: 'lottery/LUCKY_WORD_ADDED',
    CURRENT_LOTTO_CHANGED: 'lottery/CURRENT_LOTTO_CHANGED',
    LOTTO_NUMBERS_CHANGED: 'lottery/LOTTO_NUMBERS_CHANGED',
    GEN_BUTTON_CLICKED: 'lottery/GEN_BUTTON_CLICKED',
    // ADD_STORAGE_KEY: 'lottery/ADD_STORAGE_KEY',
    // ADD_STORAGE_KEYS: 'lottery/ADD_STORAGE_KEYS'
  };
  